// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztjdnvzuwpcyveilmyxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0amRudnp1d3BjeXZlaWxteXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODUzNDMsImV4cCI6MjA3MDk2MTM0M30.ULE7YKRPAqik4wsS-hwTR1yw2pWKfspCcRI-kOmD6z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});